# Generated by Django 5.2.17 on 2026-08-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text='Source system transaction ID (e.g. from an imported CSV). Optional for transactions submitted directly via the API.', max_length=64, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('account_number', models.CharField(max_length=34)),
                ('category', models.CharField(blank=True, choices=[('groceries', 'Groceries'), ('dining_out', 'Dining Out'), ('utilities', 'Utilities'), ('transportation', 'Transportation'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('shopping', 'Shopping'), ('housing', 'Housing'), ('education', 'Education'), ('miscellaneous', 'Miscellaneous')], default='', max_length=20)),
                ('category_source', models.CharField(blank=True, choices=[('ai', 'AI'), ('rule', 'Rule-based fallback'), ('manual', 'Manual')], default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['category'], name='transaction_categor_d2bef2_idx'), models.Index(fields=['timestamp'], name='transaction_timesta_20dac7_idx')],
            },
        ),
    ]
